### ISSUE TITLE
Readme GLSL touchup

### ISSUE THREAD

**Issue by mattdesl** [mikolalysenko/a-big-triangle#1]
To get it to compile on my OSX I needed to use this:

(added precision modifiers and wrapped position.xy in a vec4)

``` js
      "precision mediump float;\
      attribute vec2 position;\
      varying vec2 uv;\
      void main() {\
        uv = position.xy;\
        gl_Position = vec4(position.xy, 0.0, 1.0);\
      }",
      "precision mediump float;\
      varying vec2 uv;\
      void main() {\
        gl_FragColor = vec4(uv, 0, 1);\
      }"
```

**Comment by mikolalysenko** [comment]
Thanks, looks like this was an old typo.  This really needs to be updated to work with glslify.

**Comment by Prinzhorn** [comment]
This has long been fixed via https://github.com/mikolalysenko/a-big-triangle/commit/8e43b9b24f8e79d7cfcfd1e18221e12f5e5bb675 right?

**Comment by mikolalysenko** [comment]
Yes
