### ISSUE TITLE
cache check fix not published to npm

### ISSUE THREAD

**Issue by lfdoherty** [mikolalysenko/a-big-triangle#5]

**Comment by mariusGundersen** [comment]
I get this error in Firefox, and it looks like the cache fix will solve it:

> Error: WebGL: isBuffer: null object passed as argument bundle.js line 2731 > eval:12:23
> Error: WebGL: No further warnings will be reported for this WebGL context. (already reported 32 warnings)

**Comment by mariusGundersen** [comment]
Until this is published I will use [`gl-big-triangle`](https://www.npmjs.com/package/gl-big-triangle), which is a slightly different way of doing it

**Comment by aferriss** [comment]
FWIW I noticed this is still happening. a-big-triangle seems to be creating a new gl-buffer with every draw call. I'm not sure your check is working quite as intended. gl-big-triangle works great though!

**Comment by lejeunerenard** [comment]
The cache fix has now been published to npm as 1.0.3 (4c83e61220975a2e4dad1cfa2e29554dade13777).
